source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
# gem 'jekyll-environment-variables'
gem 'octicons', group: :jekyll_plugins
gem 'octicons_helper', group: :jekyll_plugins
gem 'jekyll-octicons', group: :jekyll_plugins
